services:
  postgres:
    image: postgres:15-alpine
    container_name: competition-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-competition_app_db}
      POSTGRES_USER: ${POSTGRES_USER:-competition_app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-C0mp3t1t10n_DB_2024_S3cur3_P@ssw0rd!}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - backend-network
      - admin-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U competition_app_user -d competition_app_db",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: competition-redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: competition-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "5050:80"
    networks:
      - admin-network
    secrets:
      - pgadmin_email
      - pgadmin_password
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: competition-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8080
    secrets:
      - db_name
      - db_user
      - db_password
    networks:
      - backend-network
      - frontend-network
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/tmp
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: competition-frontend
    ports:
      - "7788:5173"
    networks:
      - frontend-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
  admin-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:

secrets:
  db_name:
    file: ./secrets/db_name.txt
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  pgadmin_email:
    file: ./secrets/pgadmin_email.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt
